version: "3.5"
services:
  node-api:
    container_name: node-api
    build: ./node-api
    ports:
      - 3000:3000
    environment:
      - API_PORT=3000
      - AUTH_API_URL=auth.api.com
      - UNNAMED_API_URL=other.api.com
  mongo:
    container_name: mongo
    image: mongo:4.2.8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeMe123
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    name: mongo
